routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('faq', function() {
    return view('faq');
});

Route::post('files/upload','FileController@upload');
Route::get('files/{id}/{filename}','FileController@download')->name('download');
Route::resource('files','FileController',['only'=>['destroy','show','store','update']]);

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('tokens','TokenController',['only'=>['index','store','destroy']]);

resources/views/faq.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="page-header">
            <h1>Site FAQ</h1>
        </div>

        <div class="row">

            <div class="col-md-4">
                <div class="well">
                    You can find most information about this site on the page. If I missed anything, feel free to use
                    the contact form I have not made yet to contact me.<br>
                    I know documentation is a bit light, ill get around to better documentation eventually.
                </div>
            </div>

            <div class="col-md-8">

                <div class="panel-group">

                    <div class="panel panel-default">

                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" href="#collapse1">Why does this site exist</a>
                            </h4>
                        </div>

                        <div id="collapse1" class="panel-collapse collapse">
                            <div class="panel-body">
                                <p>
                                    I made this site with a friend in mind. He needed to make frequent off-site backups
                                    of one of his servers, but had an incredibly slow internet connection and aggressive
                                    bandwidth caps. He had a bash script to upload files to DropBox, but it was slow
                                    and cumbersome.<br>
                                    We were talking about the problem one day and he mentioned that he wished there was
                                    a site out there that he could just tell to "Hold This" file for a little bit. And
                                    thus the site was born.<br><br>
                                    The site is not meant to be too complicated. It has a simple web interface, an easy
                                    to use API, and that's it.
                                </p>
                            </div>
                        </div>

                    </div>

                    <div class="panel panel-default">

                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" href="#collapse2">Is it free?</a>
                            </h4>
                        </div>

                        <div id="collapse2" class="panel-collapse collapse">
                            <div class="panel-body">
                                <p>
                                    Short answer: Yes.<br>
                                    Long answer: Kinda Yes.<br>
                                </p>
                                <p>
                                    Short term I will allow users to store a maximum of 1GB per month, and I am
                                    calculating usage in timed byte-hours. Without going into too much detail, that
                                    basically means you can store a 1GB file for a month or a 30GB file for a day.
                                </p>
                                <p>
                                    Long term I will implement a paid option. I don't plan on turning a profit, but for
                                    users who want to use this commercially or whose storage requirements are greater
                                    than can be reasonably expected from a free service, I will charge at a not yet
                                    determined rate.
                                </p>
                            </div>
                        </div>

                    </div>

                    <div class="panel panel-default">

                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" href="#collapse3">Are my files safe?</a>
                            </h4>
                        </div>

                        <div id="collapse3" class="panel-collapse collapse">
                            <div class="panel-body">
                                <p>
                                    No.<br>
                                    There are safeguards in place to prevent unauthorized users from accessing your
                                    data, but you should never upload any sensitive data to a third party (in this case
                                    that is me).
                                </p>
                            </div>
                        </div>

                    </div>

                    <div class="panel panel-default">

                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" href="#collapse4">How do I use the API?</a>
                            </h4>
                        </div>

                        <div id="collapse4" class="panel-collapse collapse">
                            <div class="panel-body">
                                <p>
                                    In order to use the API you will need an <i>'API Access Token'</i>. You can manage
                                    your access tokens <a href="{{ route('tokens.index') }}">here</a>.
                                </p>
                                <p>
                                    The basic usage is fairly straightforward. The token goes in the Authorization
                                    header, but the rest is up to the implementation.<br>
                                    The available routes are as follows:
                                </p>
                                <div class="list-group">

                                    <a href="#" class="list-group-item">
                                        <h4 class="list-group-item-heading">/api/user</h4>
                                        <p>
                                            <b>GET:</b> Returns the currently logged in users info
                                        </p>
                                    </a>

                                    <a href="#" class="list-group-item">
                                        <h4 class="list-group-item-heading">/api/files</h4>
                                        <p>
                                            <b>GET:</b> Returns a list of all your files<br>
                                            <b>POST:</b> Uploads a few file
                                        </p>
                                    </a>

                                    <a href="#" class="list-group-item">
                                        <h4 class="list-group-item-heading">/api/files/{id}</h4>
                                        <p>
                                            <b>GET:</b> Returns information on a specific file<br>
                                        </p>
                                    </a>

                                </div>
                            </div>
                        </div>

                    </div>

                </div>

            </div>

        </div>


    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row">

        <div class="col-md-4">

            <div class="page-header" data-toggle="tooltip" data-placement="top" title="Does not include expired items">
                <h1>My Stats</h1>
            </div>

            <table class="table table-striped table-hover ">
                <tbody>
                <tr>
                    <th>Total Files</th>
                    <td>{{ \Auth::user()->files->count() }}</td>
                </tr>
                <tr>
                    <th>Disk Consumed</th>
                    <td>{{ \Auth::user()->disk_usage->pretty }}</td>
                </tr>
                <tr>
                    <th>Bandwidth Used</th>
                    <td> {{ \Auth::user()->bandwidth_usage->pretty }}</td>
                </tr>
                </tbody>
            </table>

        </div>

        <div class="col-md-8">

            <div class="page-header">
                <h1>My Files</h1>
            </div>

            @if(\Auth::user()->files->isEmpty())
                <div class="alert alert-info">
                    There are no files currently associated with your account
                </div>
            @else
                <table class="table table-striped table-hover ">

                    <thead>
                    <tr>
                        <th>File Name</th>
                        <th>Notes</th>
                        <th>Visibility</th>
                        <th>Downloads</th>
                        <th>Expires At</th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach(\Auth::user()->files->sortBy('clientName') as $file)
                        <tr>
                            <td><a href="{{ url('files/'.$file->id) }}">{{ $file->clientName }}</a></td>
                            <td>{{ strlen($file->notes) > 20 ? substr($file->notes,0,20).'...' : $file->notes }}</td>
                            <td>{{ $file->visibility }}</td>
                            <td>{{ $file->downloads }}</td>
                            <td>{{ $file->expires_at->format('m-d-Y') }}</td>
                        </tr>
                    @endforeach
                    </tbody>

                </table>
            @endif

        </div>

    </div>

    <div class="row">
        <div class="col-md-12">

            <div class="page-header">
                <h2>Monthly Disk Utilization</h2>
            </div>

            <div title="This takes into account expired files which have been removed less than a month ago" data-toggle="tooltip" data-placement="top" class="progress" style="margin-bottom:0;">
                <div class="progress-bar progress-bar-info" style="width: {{ \Auth::user()->monthly_utilization->raw / (10**7) }}%"></div>
            </div>

        </div>
    </div>

</div>
@endsection

@push('scripts')
<script>
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>
@endpush

resources/views/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <form action="{{ url('files') }}" method="post" enctype="multipart/form-data">

            {!! csrf_field() !!}

            <div class="row">

                <div class="col-md-4">

                    <div class="page-header">
                        <h2>Notes</h2>
                    </div>

                    <textarea name="notes" style="min-height: 60px;" class="form-control" placeholder="Check out my awesome file!{{ PHP_EOL }}(optional)"></textarea>

                </div>

                <div class="col-md-8">

                    <div class="page-header">
                        <h2>File</h2>
                    </div>

                    <input style="min-height: 60px;padding-top:18px;" type="file" class="form-control" placeholder="File" id="file" name="file">

                </div>

            </div>

            <div class="row">

                <div class="col-md-6">

                    <div class="page-header">
                        <h2>Options:</h2>
                    </div>

                    <div class="row">

                        <div class="col-md-6">

                            <h4>Expires After</h4>

                            <select name="expires_at" class="form-control">
                                <option value="1">1 Day</option>
                                <option value="7">1 Week</option>
                                <option value="30">1 Month</option>
                                <option value="365">1 Year</option>
                                <option value="0" {{ (\Auth::guest() ? "disabled" : "") }}>Never{{ (\Auth::guest() ? " (Members Only!)" : "") }}</option>
                            </select>

                        </div>

                        <div class="col-md-6">

                            <h4>Exposure</h4>

                            <select class="form-control" name="visibility">
                                <option value="public" selected>Public</option>
                                <option value="unlisted">Unlisted</option>
                                <option @if(\Auth::guest()) disabled @endif value="private">Private</option>
                            </select>

                        </div>

                    </div>

                </div>

                <div class="col-md-6">

                    <div class="page-header">
                        <h2>Pricing:</h2>
                    </div>

                    <p><b>Free</b> for beta testers</p>

                    <br>

                    <button type="button" id="submit" class="btn btn-primary pull-right">Make It So!</button>

                    @push('scripts')
                        <script>
                            $('#submit').on('click',function() {
                                $('#progressDiv').show();
                                $('#submit').attr('disabled',true);
                                $.ajax({
                                    url: '{{ url('files/upload') }}',
                                    type: 'POST',
                                    data: new FormData($('form')[0]),
                                    cache: false,
                                    contentType: false,
                                    processData: false,
                                    xhr: function() {
                                        var myXhr = $.ajaxSettings.xhr();
                                        if (myXhr.upload) {
                                            // For handling the progress of the upload
                                            myXhr.upload.addEventListener('progress', function(e) {
                                                if (e.lengthComputable) {
                                                    $('#progress').css('width',((e.loaded / e.total) * 100) + '%');
                                                }
                                            } , false);
                                        }
                                        return myXhr;
                                    }
                                }).done(function(response) {
                                        window.location.href = "{{ url('files') }}/" + response['id'];
                                    });
                            })
                        </script>
                    @endpush
                </div>

            </div>

            <div class="row" style="padding-top:40px">
                <div class="col-md-6 col-md-offset-3">
                    <div id="progressDiv" class="progress progress-striped active" style="display: none">
                        <div id="progress" class="progress-bar" style="width: 0"></div>
                    </div>
                </div>
            </div>

        </form>

    </div>
@endsection

resources/views/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">

            <div class="col-md-6">
                <div class="well">
                    {{ (!empty($File->notes) ? $File->notes : "No notes provided") }}
                </div>
            </div>

            <div class="col-md-6">
                <a href="{{ $File->download_url }}" class="btn btn-default btn-lg btn-block">Download File</a>
            </div>

        </div>

        <div class="row">

            <div class="col-md-6">
                <table class="table table-striped table-hover ">
                    <tbody>
                    <tr>
                        <th>Name</th>
                        <td>{{ $File->clientName }}</td>
                    </tr>
                    <tr>
                        <th>Size</th>
                        <td>{{ $File->size->pretty }}</td>
                    </tr>
                    <tr>
                        <th>Downloads</th>
                        <td>{{ $File->downloads }}</td>
                    </tr>
                    <tr>
                        <th>Bandwidth</th>
                        <td>{{ $File->bandwidth->pretty }}</td>
                    </tr>
                    <tr>
                        <th>Upload Date</th>
                        <td>{{ $File->created_at->format('m-d-Y') }}</td>
                    </tr>
                    <tr>
                        <th>Expires</th>
                        <td>{{ (!is_null($File->expires_at) ? $File->expires_at->format('m-d-Y') : "Never") }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>

            @if(!\Auth::guest() && !is_null($File->user) && $File->user->id == \Auth::user()->id)
                <div class="col-md-6">
                    <div class="panel-group">

                        <div class="panel panel-default" style="margin-bottom: 20px;">

                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" href="#collapse1">Administration Options</a>
                                </h4>
                            </div>

                            <div id="collapse1" class="panel-collapse collapse">

                                <ul class="list-group">

                                    <li class="list-group-item">
                                        <input onchange="updateFile()" id="expires_at" type="number" step="1" min="0" class="form-control" placeholder="Delay Expiration By Days">
                                    </li>

                                    <li class="list-group-item">
                                        <select onchange="updateFile()" id="visibility" class="form-control">
                                            <option disabled selected>Change Visibility To...</option>
                                            <option value="public">Public</option>
                                            <option value="private">Private</option>
                                            <option value="unlisted">Unlisted</option>
                                        </select>
                                    </li>

                                    @push('scripts')
                                    <script>
                                        function updateFile() {

                                            var payload = {
                                                '_method': 'PATCH',
                                                '_token': '{{ csrf_token() }}'
                                            };

                                            // Set the expires_at variable
                                            var expires_at = $('#expires_at').val();

                                            // If it is not an empty string (placeholder edited)
                                            if (expires_at !== "") {
                                                // Set the expires_at variable
                                                payload['expires_at'] = expires_at;
                                            }

                                            // Set the visibility variable
                                            var visibility = $('#visibility').val();

                                            // If the visibility is not null
                                            if (visibility !== null) {
                                                // Set the visibility variable
                                                payload['visibility'] = visibility;
                                            }

                                            $.post('{{ url('files',[$File->id]) }}',payload)
                                                .done(function() {
                                                    $('#successMessage').text("File updated successfully");
                                                    $('#success').show('slow');
                                                    setTimeout(function() {
                                                        $('#success').hide('slow');
                                                        window.location.href = '{{ url("files",[$File->id]) }}';
                                                    },2000)
                                                })
                                                .fail(function() {
                                                    $('#errorMessage').text("Updating file failed");
                                                    $('#error').show('slow');
                                                    setTimeout(function () {
                                                        $('#error').hide('slow');
                                                    },2000);
                                                });
                                        }
                                    </script>
                                    @endpush

                                    <li class="list-group-item">

                                        <button id="delete" class="btn btn-block btn-danger">Delete File</button>

                                        @push('scripts')
                                        <script>
                                            $('#delete').on('click',function () {
                                                $.post('{{ url('files',[$File->id]) }}',{
                                                    '_token': '{{ csrf_token() }}',
                                                    '_method': 'delete'
                                                }).fail(function() {
                                                    $('#errorMessage').text("Deletion of this file failed");
                                                    $('#error').show('slow');
                                                    setTimeout(function () {
                                                        $('#error').hide('slow');
                                                    },2000);
                                                }).done(function() {
                                                    $('#successMessage').text("File deleted successfully");
                                                    $('#success').show('slow');
                                                    setTimeout(function() {
                                                        $('#success').hide('slow');
                                                        window.location.href = '{{ url("/") }}';
                                                    },2000)
                                                })
                                            })
                                        </script>
                                        @endpush

                                    </li>

                                </ul>

                            </div>

                        </div>

                        <div id="error" style="display:none" class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>Error!</strong> <p id="errorMessage"></p>
                        </div>

                        <div id="success" style="display: none" class="alert alert-success">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>Success!</strong> <p id="successMessage"></p>
                        </div>

                    </div>
                </div>
            @endif

        </div>
    </div>
@endsection

resources/views/tokens.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="page-header">
            <h1>API Access Tokens</h1>
        </div>

        <div class="row">

            <div class="col-md-4">
                <div class="well">
                    On this page you can create and manage access tokens for third party applications.
                </div>
            </div>

            <div class="col-md-8">
                <table class="table table-striped">

                    <thead>
                    <tr>
                        <th style="width:40%">Key</th>
                        <th style="width:40%">Created At</th>
                        <th style="width:20%"></th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach(\Auth::user()->tokens as $token)
                        <tr id="TokenTr_{{ $token->id }}">
                            <td>{{ $token->key }}</td>
                            <td>{{ $token->created_at->format('m-d-Y') }}</td>
                            <td>
                                <button onclick="deleteToken({{ $token->id }})" class="btn btn-danger">Delete</button>
                            </td>
                        </tr>
                    @endforeach
                    <tr id="NewToken">
                        <td colspan="3">
                            <button id="NewTokenButton" class="btn btn-block btn-success">Generate New Token</button>
                        </td>
                    </tr>
                    </tbody>

                </table>
            </div>

        </div>

    </div>
@endsection

@push('scripts')
<script>

    $('#NewTokenButton').on('click',function() {
        $.post('{{ route('tokens.store') }}',{
            '_token': '{{ csrf_token() }}'
        })
            .done(function(Response) {
                $('#NewToken').before(
                    '<tr id="TokenTr_' + Response['id'] + '">' +
                        '<td>' + Response['key'] + '</td>' +
                        '<td>Just Now</td>' +
                        '<td>' +
                            '<button onclick="deleteToken(' + Response['id'] + ')" class="btn btn-danger">Delete</button>' +
                        '</td>' +
                    '</tr>'
                );
            });
    });

    function deleteToken(TokenID) {
        $.post('{{ route('tokens.destroy',null) }}/' + TokenID,{
            '_method': 'DELETE',
            '_token': '{{ csrf_token() }}'
        })
            .done(function() {
                $('#TokenTr_' + TokenID).remove();
            });
    }

</script>
@endpush